apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: myharbor.apps.211-34-231-93.nip.io/edu/edu_baseinfo
  newTag: "20240417084447"
