apiVersion: v1	
kind: Service	
metadata:	
  name: backend_test
  labels:
    app: backend_test
spec:	
  ports:	
  - port: 80	
    targetPort: 8080
    name: http
  selector:	
    app: backend_test
  type: ClusterIP
