apiVersion: v1	
kind: Service	
metadata:	
  name: backendtest
  labels:
    app: backendtest
spec:	
  ports:	
  - port: 80	
    targetPort: 8081
    name: http
  selector:	
    app: backendtest
  type: ClusterIP
